title: Anastasia Riana
logo: /assets/img/109006234-1(1).png
description: Standards & Data Services Specialist @Faria Education Group | B.Sc @NTHU | Google Certified Data Analyst 
show_downloads: false
theme: jekyll-theme-minimal
