title: Anastasia Riana
logo: /assets/img/Untitled design.png
description: Associate Technical Consultant @Fime | B.Sc @NTHU | Google Certified Data Analyst 
show_downloads: false
theme: jekyll-theme-minimal

# New Content Sections or Settings
baseurl: "/"
url: "https://yourgithubusername.github.io"  # If your site is hosted on GitHub Pages
author: "Anastasia Riana"
email: "your.email@example.com"
twitter_username: "your_twitter_handle"
github_username: "your_github_handle"
linkedin_username: "your_linkedin_handle"

# Adding a personal intro/biography section to display on the site
intro: |
  Hi! I'm Anastasia Riana, an Associate Technical Consultant at Fime. 
  With a background in data analysis and technical consulting, I strive to innovate in the payment services industry.

# To include the README as your site's content
markdown: kramdown

# Define where your content comes from (if not README.md):
content:
  path: "README.md"   # If your content is inside the README file

# Enable other configurations
paginate: 5
paginate_path: "page/:num"

# Adding social media links or footer links
social_links:
  twitter: "https://twitter.com/your_twitter_handle"
  github: "https://github.com/your_github_handle"
  linkedin: "https://www.linkedin.com/in/your_linkedin_handle"

# You can also enable analytics, like Google Analytics if you want
google_analytics: "UA-XXXXX-Y"
