title: Anastasia Riana
logo: /assets/img/109006234-1(1).png
description: B.Sc in Electrical Engineering & Computer Science @National Tsing Hua University | Data Specialist Intern @Faria | Google Certified Data Analyst 
show_downloads: false
theme: jekyll-theme-minimal
