title: Anastasia Riana
logo: /assets/img/Untitled design.png
description: Associate Technical Consultant @Fime | B.Sc @NTHU | Google Certified Data Analyst 
show_downloads: false
theme: jekyll-theme-minimal
