title: Anastasia Riana
logo: /assets/img/109006234-1(1).png
description: Associate Technical Consultant @Fime | B.Sc @NTHU | Google Certified Data Analyst 
show_downloads: false
theme: jekyll-theme-minimal
